<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KaryaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('karya')->insert([
            [
                'id_admin' => 1,
                'id_stan' => 1,
                'id_pameran' => 1,
                'id_kategori' => 6,
                'judul' => 'Barelang F1',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/11q4ZqCcfkbBgkGJteeejc5sErN_-GjfB/view?usp=drivesdk',
                'gambar_poster' => 'https://drive.google.com/file/d/1MBvScHDRBOrbcf1ijuN_pcOLGwWEC30D/view',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 2,
                'id_pameran' => 1,
                'id_kategori' => 6,
                'judul' => 'GESTURA',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/fIldWDDILpk?si=qAXt_5igoxrx8tOp',
                'gambar_poster' => 'https://drive.google.com/file/d/10mZ2swjDUhu0aCBpJxEAwrugstiK1Dta/view',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 3,
                'id_pameran' => 1,
                'id_kategori' => 6,
                'judul' => 'Security Patrol Robot (mipam)',
                'deskripsi' => '-',
                'tautan' => '',
                'gambar_poster' => 'https://drive.google.com/file/d/1_nhbZdzSi22kxcW0NZgVWcIvSayhJsfJ/view',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 4,
                'id_pameran' => 1,
                'id_kategori' => 6,
                'judul' => 'BarelangFC - An Edge-AI Powered Goal-Line Detector Using Jetson Nano for Enhanced Refereeing in HSL',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/15lKZAZj2y0ItsgNWt6lIR_i2hZEyc1Z7/view?usp=drivesdk',
                'gambar_poster' => 'https://drive.google.com/file/d/1UKcRiGMNDdcr9V5x41CGMW6B8PiymjlZ/view',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 5,
                'id_pameran' => 1,
                'id_kategori' => 6,
                'judul' => 'BARELANG 63',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1Yu5uTptqJD8AQGn4eqpMebh7SgAPTO4I/view?usp=drivesdk',
                'gambar_poster' => 'https://drive.google.com/file/d/1b0VoQDDdyB9l0euAYTr67Lu8Kz57TfQq/view',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 6,
                'id_pameran' => 1,
                'id_kategori' => 6,
                'judul' => 'Chair and Table Transporter',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1MlPuxxxgGJLyUiDMV5R7IWeR2nelPx_v/view',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 7,
                'id_pameran' => 1,
                'id_kategori' => 6,
                'judul' => 'AGV SUMITOMO',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/VRztKMxd8rg?feature=shared',
                'gambar_poster' => 'https://drive.google.com/file/d/1nPF4FyOv32EFlOef59DviB5LgqmMjA8c/view',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 8,
                'id_pameran' => 1,
                'id_kategori' => 6,
                'judul' => 'R2PB (Robot Pemandu Pencarian Buku)',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1_ZkZuLgwyOjzM_hQhgd1C3940qS53-pX/view',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 9,
                'id_pameran' => 1,
                'id_kategori' => 7,
                'judul' => 'The Inscale',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/M-h58r04Yvs?feature=shared',
                'gambar_poster' => 'https://drive.google.com/file/d/1JSiWeX6pU676Zj8IWNDghhtd20B6FhJH/view',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 10,
                'id_pameran' => 1,
                'id_kategori' => 7,
                'judul' => 'Rancang Bangun Timbangan Kadar Lemak Cerdas Berbasis Bioelectrical Impedance Analysis (BIA)',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1zRC12TqcrnL0NDVJwn5SmmmrNhD0FJkz/view?usp=drivesdk',
                'gambar_poster' => 'https://drive.google.com/file/d/19Ohsq_Q6wN5OA_5eMGjI9b56wy-5wHuO/view',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 11,
                'id_pameran' => 1,
                'id_kategori' => 7,
                'judul' => 'AERO',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=EvZ7eC4ecbA&list=PL5xtYxcwBBrfAsJjweSaFJ6zftQzXxT7Z&index=1',
                'gambar_poster' => 'https://drive.google.com/file/d/1viqwTuBfjtH5-V31kiaUojEukJGveXD7/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 12,
                'id_pameran' => 1,
                'id_kategori' => 7,
                'judul' => 'DELIVERY ROBOT',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1By8Gcs-Bm_cIvLRZ8VvYV_CINWZ5lP5e/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 13,
                'id_pameran' => 1,
                'id_kategori' => 7,
                'judul' => 'Aeroxy-AI',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/dX7AhHAxc5E?si=1AH1YYpRlY2jPhxQ',
                'gambar_poster' => 'https://drive.google.com/file/d/1PsuSE4z1meWWegK4vZNwfxOEKIG0WThd/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 14,        
                'id_pameran' => 1,
                'id_kategori' => 7,
                'judul' => 'Barelang Sky Force',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=CbJKxtnjLL4',
                'gambar_poster' => 'https://drive.google.com/file/d/1mJoNjWEuOJn0cgwqV_RMoKvDM0f5vApb/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 15,
                'id_pameran' => 1,
                'id_kategori' => 7,
                'judul' => 'WEB-BASED BIOFLOC MONITORING AND PH CONTROL SYSTEM',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1QMvoi5mXV0YqCFoCndUg33Bb6feLU0ZA/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 16,
                'id_pameran' => 1,
                'id_kategori' => 8,
                'judul' => 'Real-time AI for Hand-Tracking',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1qRmK-AKmOxilaVQ_FVX4yehGOUY5UmsU/view?usp=sharing',
                'gambar_poster' => 'https://drive.google.com/file/d/1QIrsKgsDmxp3gLKBWykwlY8UtqO9rAh3/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 17,
                'id_pameran' => 1,
                'id_kategori' => 5,
                'judul' => 'SISTEM AUTO GATE BERBASIS UHF LONG RANGE READER UNTUK PENINGKATAN EFISIENSI DAN KEAMANAN',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=FrqQsxrBV_0',
                'gambar_poster' => 'https://drive.google.com/file/d/19m19JKXR_rKpaz2ZfAxplF6YrQ_LQB3s/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 18,
                'id_pameran' => 1,
                'id_kategori' => 5,
                'judul' => 'Mesin Pengaduk Masakan Otomatis',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=VJTVuoLi-0g',
                'gambar_poster' => 'https://drive.google.com/file/d/1OiGDcwyzwLbOfiIuejHPtvgK07Dk84w4/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 19,
                'id_pameran' => 1,
                'id_kategori' => 5,
                'judul' => 'Control Aktuator Bioflok',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=YcPWrX4l1II',
                'gambar_poster' => 'https://drive.google.com/file/d/1g3vbUXirMhRGtTOkjndJup5xaNZ0IBzf/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 20,
                'id_pameran' => 1,
                'id_kategori' => 5,
                'judul' => 'Cartesio-M3',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=befUsGvZyHw',
                'gambar_poster' => 'https://drive.google.com/file/d/1Gesu9RTsF_DSjKLmVJyRu35G4IKcx2MY/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 21,
                'id_pameran' => 1,
                'id_kategori' => 5,
                'judul' => 'BROMO - Building Room ON/OFF Monitoring & Operation',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=_tYTpqZ80QI',
                'gambar_poster' => 'https://drive.google.com/file/d/1nY3a41ET0S8cabrw99QAXHfMnKggdVeA/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 22,
                'id_pameran' => 1,
                'id_kategori' => 5,
                'judul' => 'Polibatam Library',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1Y1a4p7ihuAGIh1H48YJB041-_um6P8v8/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 23,
                'id_pameran' => 1,
                'id_kategori' => 8,
                'judul' => 'Polimdo 1',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=smt8Bc5NqNM',
                'gambar_poster' => 'https://drive.google.com/file/d/1Mm8KHpC1BbXTSR_IIHAa27g9-xutKBHg/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 24,
                'id_pameran' => 1,
                'id_kategori' => 9,
                'judul' => 'Polimdo 2',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=95rmXUDriuE',
                'gambar_poster' => 'https://drive.google.com/file/d/1gx4n32h5qs1ay9PyXIwWVPEfR_rl-27m/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 25,
                'id_pameran' => 1,
                'id_kategori' => 5,
                'judul' => 'SITANI',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=tvvKfJ7JDXk',
                'gambar_poster' => 'https://drive.google.com/file/d/1wOu_bCwkTnxyee3HO1psacWP1S64NCfu/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 26,
                'id_pameran' => 1,
                'id_kategori' => 12,
                'judul' => 'TRM POLIMDO',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1bcL7U8I-LvDZcm12hKkTqGwKzwnmg9Sw/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 27,
                'id_pameran' => 1,
                'id_kategori' => 12,
                'judul' => 'Tim EmisiKu',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1x6fnRMeVSZ3ZB8o8AdH4eryyv-KmmjR-/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 28,
                'id_pameran' => 1,
                'id_kategori' => 7,
                'judul' => 'Platform Aerial ULV-Fogging dengan Kontrol Droplet Adaptif untuk Aplikasi Biostimulan dan Mikroba Hidup Presisi Kanopi',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1TAYuJ3Y4aItX3hl43hS4psYNExEpWS9d/view?usp=sharing',
                'gambar_poster' => 'https://drive.google.com/file/d/1VL7BntuawTdyFBxeeN3rO7yZhb1LImHu/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 29,
                'id_pameran' => 1,
                'id_kategori' => 2,
                'judul' => 'CodeX',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1Zc3_BpAwOH5EANNlvA1jHyOimH2dtWgT/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 30,
                'id_pameran' => 1,
                'id_kategori' => 6,
                'judul' => 'ROV Crovodile Team',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1HGCUklQzlDPXXpQ354i40KFC7JrdOgVe/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 31,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'Selais Narasena Unri',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=dAjl94DcrQ0',
                'gambar_poster' => 'https://drive.google.com/file/d/1mfNSDJ8YkLWaScja_k_LCG0Hd5urSdM4/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 32,
                'id_pameran' => 1,
                'id_kategori' => 12,
                'judul' => 'Selais Thermonav UNRI',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1ZX5_R1RVNy0Id4YD-RySlXAzrc3NmzcH/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 33,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'FAMandala UNRI',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=zg4p9-w2oTI',
                'gambar_poster' => 'https://drive.google.com/file/d/1SUsDRmlUCNtOITWVUKMMCC_0oIBvEx18/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 34,
                'id_pameran' => 1,
                'id_kategori' => 12,
                'judul' => 'Melontiok',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=1Lw_qVqlZZI',
                'gambar_poster' => 'https://drive.google.com/file/d/1UtNgiQ_quZo4bF3EDQ0WPZ16N8dRJiJG/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 35,
                'id_pameran' => 1,
                'id_kategori' => 7,
                'judul' => 'Energy and Environment Challenge',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1aE3lPUTKBg5EaJ20q8X7MlBVHaZ5Iv1b/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 36,
                'id_pameran' => 1,
                'id_kategori' => 1,
                'judul' => 'IoT GUARDIAN',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=gOBjO4dmSt8',
                'gambar_poster' => 'https://drive.google.com/file/d/10t1GXD1mArUHdYDL7lA29uDHw9DgeftI/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 37,
                'id_pameran' => 1,
                'id_kategori' => 9,
                'judul' => 'Ibnu Sina Batam',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1NuACzRMX9ICfzrKL9EUPiIGb32R4-Xzb/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 38,
                'id_pameran' => 1,
                'id_kategori' => 1,
                'judul' => 'Intelecta Reformasi Team',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=Snrdw3zcc8g',
                'gambar_poster' => 'https://drive.google.com/file/d/1Hf02DHtajUA5Pblw6EMEaK6yZ9Jl2Prl/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 39,
                'id_pameran' => 1,
                'id_kategori' => 5,
                'judul' => 'Solar Optimizer using MPPT Boost for Maximizing Photovoltaic Output',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1RtztbWwqc7HoBCdICIdiZ9mEswLAnUBW/view?usp=sharing',
                'gambar_poster' => 'https://drive.google.com/file/d/1x2Pg-9RaJJblhfNNhAA8SiQnPmPZBDrq/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 40,
                'id_pameran' => 1,
                'id_kategori' => 5,
                'judul' => 'Mech4Sketch-Cartesian',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=gOLcGxQmS6M',
                'gambar_poster' => 'https://drive.google.com/file/d/1yfGaL0hKMczO5dguIjxLuapyyXAp7qLU/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 41,
                'id_pameran' => 1,
                'id_kategori' => 9,
                'judul' => 'ECG MEKACU',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1URLpj1N5Osx5tXM2pkizelLForJkRcRW/view',
                'gambar_poster' => 'https://drive.google.com/file/d/1WpR9213njQ3mgv_sAA5MKWmKlzPTXJla/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 42,
                'id_pameran' => 1,
                'id_kategori' => 9,
                'judul' => 'Barelang FC Robocup Team',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/13VQuQ8zvJEfqjv0yHwUmXjiC42VHcbfH/view?usp=drivesdk',
                'gambar_poster' => 'https://drive.google.com/file/d/1Fvfgv1Zv_pEuFN9UWfzuatISAdd8JDbe/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 43,
                'id_pameran' => 1,
                'id_kategori' => 9,
                'judul' => 'Calibra Core',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/182_FdC5Rnwzskda7E47tgu1O0w0TcTa4/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 44,
                'id_pameran' => 1,
                'id_kategori' => 9,
                'judul' => 'Harap Harap CEMAS',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/11pj_lQxU_VLEG-iAhnPcfMr_pF-MUSjk/view',
                'gambar_poster' => 'https://drive.google.com/file/d/1cfBArg45cFk9-LrXolcF72_keDxujt3k/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 45,
                'id_pameran' => 1,
                'id_kategori' => 9,
                'judul' => 'THE QUALITY GUARDIANS',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1EceTAQG70SyGVnaitLHZCMtrIOMIBtLK/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 46,
                'id_pameran' => 1,
                'id_kategori' => 9,
                'judul' => 'AIRCRAFT',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/HtbzU6dKjig?si=Llv1-5OTIAma_Ah1',
                'gambar_poster' => 'https://drive.google.com/file/d/1TBRD2bLeNsHxPe3w-EGBY4HJ41A05lx8/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 47,
                'id_pameran' => 1,
                'id_kategori' => 9,
                'judul' => 'SIMON SAYS FOOTSTEP MEMORY GAME',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1YgSUzLJuHyl7uy1nB02ZqL0zSoQNglvJ/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 48,
                'id_pameran' => 1,
                'id_kategori' => 9,
                'judul' => 'Barelang Hydromodelling team',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1GK3gM6D0i89BUxdabaIG5xMkgBRh0CiI/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 49,
                'id_pameran' => 1,
                'id_kategori' => 1,
                'judul' => 'PBL-TRPL409 ',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/4mkIFQ3xdlc?si=g9c7GmN_ey1DU0aT',
                'gambar_poster' => 'https://drive.google.com/file/d/1g4IUcCeiDP9w1nWSJATOjY0Z1Z1ke-cq/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 50,
                'id_pameran' => 1,
                'id_kategori' => 1,
                'judul' => 'PBL TRPL-402',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/15nKB6ORvl4sgj-z9kEQm3RlIPjrDDtpm/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 51,
                'id_pameran' => 1,
                'id_kategori' => 1,
                'judul' => 'Sistem Monitoring dan Kontrol Smart Akuakultur Berbasis IoT',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1Sum2czATP9LLs2PTEBwCeJpYSDUjGQYX/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 52,
                'id_pameran' => 1,
                'id_kategori' => 1,
                'judul' => 'ORCA TRPL-401',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/4mkIFQ3xdlc?si=g9c7GmN_ey1DU0aT',
                'gambar_poster' => 'https://drive.google.com/file/d/1_JySFuz5rbNCaxYRE7ziymZVXlLjMLtq/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 53,
                'id_pameran' => 1,
                'id_kategori' => 1,
                'judul' => 'BMITracker',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/_e6wZYAjLQk?si=tuyI5L-aSnbfeX4L',
                'gambar_poster' => 'https://drive.google.com/file/d/1LLgbKrSpUAvC02RO0QjXx1M0ZWkEyePP/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 54,
                'id_pameran' => 1,
                'id_kategori' => 1,
                'judul' => 'I-SCAPE (Integrasi Sistem Control Portable Hemat Energi) ',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/-M13DSomoM4?si=_ZBge7b2-AWxiRkY',
                'gambar_poster' => 'https://drive.google.com/file/d/12mHbiEkro8KUkCDbcdpHBDX7LwE9sAru/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 55,
                'id_pameran' => 1,
                'id_kategori' => 1,
                'judul' => 'Smart Pressure Calibration Base on IoT',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/-M13DSomoM4?si=_ZBge7b2-AWxiRkY',
                'gambar_poster' => 'https://drive.google.com/file/d/1VUJmckXFys9ysiS6iiXu8KzRZ3seTy33/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 56,
                'id_pameran' => 1,
                'id_kategori' => 1,
                'judul' => 'TOSAB (Tongkat Sakti Aseli Batam)',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/b34EOAvZoWs?feature=shared',
                'gambar_poster' => 'https://drive.google.com/file/d/1kCRVJ3FVWpS0invK9Q18_w0WM1O965AQ/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 57,
                'id_pameran' => 1,
                'id_kategori' => 1,
                'judul' => 'Aero Sense',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1XthT9yeiZfHD7MxBvxc-Tg9qWkc3oS36/view?usp=drivesdk',
                'gambar_poster' => 'https://drive.google.com/file/d/1QMoPYbOKVkC26hpdIHTB3yNAHTYYyNZz/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 58,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Relawan Pajak Untuk Negeri (Renjani) 2026 - AK4C Malam',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 59,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Relawan Pajak Untuk Negeri (Renjani) 2026 - AK4C Malam',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 60,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'BUSINESS DEVELOPMENT SERVICES',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 61,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Perancangan dan Implementasi Sistem Administrasi Perkantoran Berkelanjutan ABT 2D Malam',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 62,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Venture & Scale Up Lab Integrated Venture Development for Market Expansion & Start-Up Creation',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 63,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Venture & Scale Up Lab Integrated Venture Development for Market Expansion & Start-Up Creation',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 64,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Pengembangan Sistem Jabatan Terintegrasi Berbasis Analisis Jabatan untuk Meningkatkan Kinerja Organisasi',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 65,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Venture & Scale-Up Lab',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 66,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Venture & Scale-Up Lab',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 67,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Perancangan Sistem Jabatan berdasarkan Analisis Jabatan',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 68,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Proses Bisnis Freight Forwarding di Batam (CDIO) - Kelas Pagi A',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 69,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Optimalisasi Perencanaan & Pengendalian Logistik - Prodi DB Semester 2 Pagi dan Malam',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 70,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Optimalisasi Perencanaan & Pengendalian Logistik - Prodi DB Semester 2 Pagi dan Malam',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 71,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'PBL CDIO - BUSINESS DEVELOPMENT SERVICES - AM 4C MALAM',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 72,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'PBL CDIO - BUSINESS DEVELOPMENT SERVICES - AM 4C MALAM',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 73,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'PBL CDIO AM6A Pagi Pembuatan Equity Analisis Report',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/ueG6sdf1i94?si=JMJxhsKIrvTmGGKQ',
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 74,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'PBL CDIO AM6A Pagi Pembuatan Equity Analisis Report',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1DyG1yf05M9DEm_TZTDy-HtHkRICtz1Id/view?usp=drivesdk',
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 75,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Feasibility study Pengembangan Pelabuhan Laut di Kota Batam',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 76,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Proses Bisnis Freight Forwarding di Batam (CDIO) - Kelas Pagi C',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 77,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'ABT 4C MALAM-Pengembangan Sistem Jabatan Terintegrasi Berbasis Analisis Jabatan untuk Meningkatkan Kinerja Organisasi',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 78,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'ABT 4C MALAM-Pengembangan Sistem Jabatan Terintegrasi Berbasis Analisis Jabatan untuk Meningkatkan Kinerja Organisasi',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 79,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Stock Rising Game',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1AX6TtD70N68VrrBXbuZgAX3eWt_n5L3s/view',
                'gambar_poster' => 'https://drive.google.com/file/d/1jpRQ6SRHgbLF8zJcQ_p72uARyQ-cbu5P/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 80,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'ABT-AT3',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/qp29ylUyK6Q?feature=shared',
                'gambar_poster' => 'https://drive.google.com/file/d/1pHP6997Bphqgt1EZLAq_1PNa1Tw78Qxd/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 81,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'ABT-AT2',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1RzS9Bw8YP1VWsawtaiRc4W9crHhw56oI/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 82,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Kelompok 1 LPI 4B Pagi',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1yma4VBFlvu2gYA_FL_sgrysgga8VcidH/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 83,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Asbistermorn',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1MagWet_nUD5Retn2aMMkcPMP4_Ca7FhZ/view?usp=drivesdk',
                'gambar_poster' => 'https://drive.google.com/file/d/1gylUDk2bu5NEE9iL_yJ2xJFn5j6RT_7P/view?usp=drivesdk',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 84,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'NextGen CEO',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1SFfBcgv9SDuUIgbtjMm9vJ_ditSg_7gB/view',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 85,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'LOGICORE',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1O0STMaSv8TOimDQpoLCSQz3Ot40HksZZ/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 86,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'EGITEAM',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1xeoV8nJaqWVcIbU0aY5GsNSP7R7Huiw_/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 87,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Green Office - Free The Sea',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1RMeOj0yh4pHIy3cD9KCSxW835okKzgZB/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 88,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Kelompok 5',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1dRo2lAQL4hCcbxmGtGNHuk8D-PE-KgY4/view?usp=drivesdk',
                'gambar_poster' => 'https://drive.google.com/file/d/1ycePLK_rEOasskijQFE9BNeqeROStuhc/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 89,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Venividici',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1mpfP0YhWBt5T0k1mLHfpJTHaDHBcZG6u/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 90,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'GRENOVA (Green Innovation)',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1DOrmvso1iYD7yq81BLvO1vGEXdrVlTxW/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 91,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'Nexaport',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1wTRfaaMbv4C8KuA4nMRxqcaaD6x_XvrF/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 92,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'PENGMAS SERIP 360',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1cbxbaqiEJKbkkLUryk1f879vTdeMsn3T/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 93,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'ACCTIVE',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1owYWiUbm58ZgaeScbMDRH9ONFESldLeI/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 94,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => 'BUSINESS DEVELOPMENT SERVICES',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1GAv49QjECTO7XrS7Nj37-_hrXvr1_NKz/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 95,
                'id_pameran' => 1,
                'id_kategori' => 11,
                'judul' => '6D-M-1',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1V6hw6F9kEDiZ47n9WgMe3T6fOGnDfovs/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 96,
                'id_pameran' => 1,
                'id_kategori' => 12,
                'judul' => 'METALLOY',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/ZGFcLSB4PU0?si=JKDeDq7Af_N3Da4s',
                'gambar_poster' => 'https://drive.google.com/file/d/1wg5f3YM3x8D94XsiI2wjBPtBd3J39H4Y/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 97,
                'id_pameran' => 1,
                'id_kategori' => 12,
                'judul' => 'Bauxite Mineral',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/126GU_gFpoyH6vdvP7ZWAlTGaq5Kx_ST4/view?usp=drivesdk',
                'gambar_poster' => 'https://drive.google.com/file/d/1uoUVEdz2NetitoGNYJWnQtEQMI-GKtWg/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 98,
                'id_pameran' => 1,
                'id_kategori' => 12,
                'judul' => 'Group 8 (Second Semester) Geomatics Technology',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/12R07xMNIK-I0TGXBqbiWli5JXQ1PMPSx/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 99,
                'id_pameran' => 1,
                'id_kategori' => 12,
                'judul' => 'Nyawit King',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/LMoLl2aGCmU?si=zcNKvR2Y-Zf7SsAk',
                'gambar_poster' => 'https://drive.google.com/file/d/1boBDdh76lPVLsDoIEQzB3GnvywzW-Ftp/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 100,
                'id_pameran' => 1,
                'id_kategori' => 12,
                'judul' => 'Kelompok 3',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/12U00DBl34P2kAC2DMDdndglGj3DA_60P/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 101,
                'id_pameran' => 1,
                'id_kategori' => 12,
                'judul' => 'TIM MANG',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 102,
                'id_pameran' => 1,
                'id_kategori' => 12,
                'judul' => 'Electromz',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 103,
                'id_pameran' => 1,
                'id_kategori' => 4,
                'judul' => 'PBL-RKS404',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1iZap9AHU2CG5bVjMwlHdZ8rZwYeAd2Bf/view',
                'gambar_poster' => 'https://drive.google.com/file/d/1zyxIdDphKKlnwvQdEEKK_M48OUaqaM_K/view?usp=drivesdk',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 104,
                'id_pameran' => 1,
                'id_kategori' => 4,
                'judul' => 'PBL RKS 413',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/EKSHnLrGW5Q?si=aYHzhZcNtF1XHjb-',
                'gambar_poster' => 'https://drive.google.com/file/d/1UpJP9lpnibQJlOK258y6jxktmDjvw5tt/view?usp=drivesdk',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 105,
                'id_pameran' => 1,
                'id_kategori' => 4,
                'judul' => 'PBL RKS-408',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/EKSHnLrGW5Q?si=aYHzhZcNtF1XHjb-',
                'gambar_poster' => 'https://drive.google.com/file/d/1beGVsWyHypA0ZFhdBVQJrBg_mmkM3kSf/view?usp=drivesdk',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 106,
                'id_pameran' => 1,
                'id_kategori' => 4,
                'judul' => 'PBL RKS-410',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1tG7MOB1WVXes6ekq6N_2wAa0p_t95Z0U/view?usp=drivesdk',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 107,
                'id_pameran' => 1,
                'id_kategori' => 4,
                'judul' => 'PBL-RKS516',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/TF2r-DStxZE?si=BTjIGL6SeIgCg2J3',
                'gambar_poster' => 'https://drive.google.com/file/d/1rBTfiLA72zCinbnnDo-G6if0Q8CierK_/view?usp=drivesdk',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 108,
                'id_pameran' => 1,
                'id_kategori' => 4,
                'judul' => 'PBL - RKS 601',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/TF2r-DStxZE?si=BTjIGL6SeIgCg2J3',
                'gambar_poster' => 'https://drive.google.com/file/d/1UaAe6U0DiyLgSelgawyBEsXNADfbSdKq/view?usp=drivesdk',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 109,
                'id_pameran' => 1,
                'id_kategori' => 4,
                'judul' => 'RKS 407',
                'deskripsi' => '-',
                'tautan' => 'https://m.youtube.com/watch?v=ik_xI2bQfi0',
                'gambar_poster' => 'https://drive.google.com/file/d/1hS1aH_yHx2DBhlnNAHOs9foj2zWuWZd5/view?usp=drivesdk',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 110,
                'id_pameran' => 1,
                'id_kategori' => 4,
                'judul' => 'PBL-RKS401',
                'deskripsi' => '-',
                'tautan' => 'https://m.youtube.com/watch?v=nbT_DTatgzw&pp=iggCQAE%3D',
                'gambar_poster' => 'https://drive.google.com/file/d/17vEYOOzuZ_ZJfJtyOTuwdMcMtZ2wRMEG/view?usp=drivesdk',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 111,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'Bezalel Geotech',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1lJtEjvoKdarbuHlCHmUKl0TalpuU8tvv/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 112,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'BARELANG MARINE ROBOTICS TEAM (BMRT)-VTOL',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1x0rVXNsSrGEsxcNSAthub0JYNsvQz0NZ/view',
                'gambar_poster' => 'https://drive.google.com/file/d/16fojwzfMrdhuKEcagsgVBTZ11-xr1q7o/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 113,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'Barelang FC',
                'deskripsi' => '-',
                'tautan' => 'https://m.youtube.com/watch?v=EV2s8ytlmaI',
                'gambar_poster' => 'https://drive.google.com/file/d/1u7eIWUU7ixF3NVdhF4qnSV2Zhyj6HxHA/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 114,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'Barelang V',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/iZfrg5qFQJ4?si=-39ymULJItYLGGJZ',
                'gambar_poster' => 'https://drive.google.com/file/d/1vtkkTuBfo3pVaLkb0Uv_n3b42eFyj4nS/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 115,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'Growora',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/iZfrg5qFQJ4?si=-39ymULJItYLGGJZ',
                'gambar_poster' => 'https://drive.google.com/file/d/1jWihXgXJ0K9J2cNGKn1WaV0SxH5H7x1T/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 116,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'PBL Group 18',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/yRvVE8hRrAY?si=HiNuWR1_zGg9YzbD',
                'gambar_poster' => 'https://drive.google.com/file/d/1muCRG-E5EK2_IEAgMdg0u3OGx42LW95-/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 117,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'PBL02GM11',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/11iisVrMnXKn2zoeKShhOfz_AmbWVfoGf/view?usp=drivesdk',
                'gambar_poster' => 'https://drive.google.com/file/d/1RRU5n2t_3TvJnMkpKXZ7NBN68HBQc02p/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 118,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'Group 6 PBL02GM11',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/a3lnahgmnrQ?si=8s8Urc63ZMx69d6C',
                'gambar_poster' => 'https://drive.google.com/file/d/1JfRB_dMeM9vNbtHWbrh6bN3QLZQclhoe/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 119,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'One Family',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/11bQ3qwvSblqCk0ZRmd63qaVZitOStD1b/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 120,
                'id_pameran' => 1,
                'id_kategori' => 8,
                'judul' => 'PROTOTYPE BOWL FEEDER WITH AUTOMATION SYSTEM',
                'deskripsi' => '-',
                'tautan' => 'https://m.youtube.com/watch?v=GHyTAw4zPqs',
                'gambar_poster' => 'https://drive.google.com/file/d/1fJLi_PnEgYVghCEcQ2ei5aEoYJPQOVgT/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 121,
                'id_pameran' => 1,
                'id_kategori' => 8,
                'judul' => 'SIMON SAYS FOOTSTEP MEMORY GAME ARDUINO',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/a3lnahgmnrQ?si=VuxHpeRWOZcDukFW',
                'gambar_poster' => 'https://drive.google.com/file/d/1FLGM2z6XRK6bRgOiZ8Wccf_gwL0XlnnP/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 122,
                'id_pameran' => 1,
                'id_kategori' => 8,
                'judul' => 'Barelang FC FIRA Team',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/g3dGVEKKImk?feature=shared',
                'gambar_poster' => 'https://drive.google.com/file/d/1EtBbVtHrjul9t34y8zWLIyKZKi9BH4wI/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 123,
                'id_pameran' => 1,
                'id_kategori' => 8,
                'judul' => 'Low Cost Inteligent Automation (LCIA)',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/W8GAt2S9uLU?si=lu9WYhsp8nXQhJOd',
                'gambar_poster' => 'https://drive.google.com/file/d/1jkjoRiUmvtvxYZfEjmjxC1LxHFIBbn87/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 124,
                'id_pameran' => 1,
                'id_kategori' => 8,
                'judul' => 'Industrial ARM Robot',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/Awowy24z7jM',
                'gambar_poster' => 'https://drive.google.com/file/d/1qOS92iRJbHglbPURDdyfBPMrsg_hQQC_/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 125,
                'id_pameran' => 1,
                'id_kategori' => 3,
                'judul' => 'Metaverse Polibatam',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/3uYCjqKmc24?si=JbWWPROS72zknDJ_',
                'gambar_poster' => 'https://drive.google.com/file/d/1LyVULKNOdkWG9qbvyxlqBMyZ6N0jjgqg/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 126,
                'id_pameran' => 1,
                'id_kategori' => 3,
                'judul' => 'TRM618',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/0g62HIQz58Q?si=CBBXTzgJD1kIESbN',
                'gambar_poster' => 'https://drive.google.com/file/d/1y3KMZGtas4ZheE55CSjlSWRY7CbYvno3/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 127,
                'id_pameran' => 1,
                'id_kategori' => 3,
                'judul' => 'AN 211',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/g2_MAdxF4wE?si=q1JTjSafd_KsoYtZ',
                'gambar_poster' => 'https://drive.google.com/file/d/14vHy4JrzuTpe-gdskFQBTOgMLCZXiW7u/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 128,
                'id_pameran' => 1,
                'id_kategori' => 3,
                'judul' => 'PBLAN 603',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1WZ4iXQd37F6eaGQNoxWLQXY2x5DG1shj/view?usp=sharing',
                'gambar_poster' => 'https://drive.google.com/file/d/1-CJ20h0PjwG_8asTkAa3k1BUaAmtG13_/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 129,
                'id_pameran' => 1,
                'id_kategori' => 3,
                'judul' => 'PBLAN-605',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1Il-u2H_aVcvsUwFWdsjRz-mU8Nqo7EWa/view',
                'gambar_poster' => 'https://drive.google.com/file/d/1V2ONmou2RIoU1Jt5b3kQpuHDb4rqIEGG/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 130,
                'id_pameran' => 1,
                'id_kategori' => 3,
                'judul' => 'HAMINSATU',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1zF6LhGvhy2F57whhvdsZw1JCt-eNwzik/view',
                'gambar_poster' => 'https://drive.google.com/file/d/1-FFdZHHSZ4bzIwMPxGA2VONecSxIZ6Jp/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 131,
                'id_pameran' => 1,
                'id_kategori' => 3,
                'judul' => 'PBLAN-605 Cutscene Gim 3D Find Patria',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/muSifmnXTvY?si=dopMDOPTyOZkQMVt',
                'gambar_poster' => 'https://drive.google.com/file/d/1U7CVp_KmxJyqu9aPF53qa-tF79AMV9Ux/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 132,
                'id_pameran' => 1,
                'id_kategori' => 3,
                'judul' => 'TRM407B1',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/19i2Xe36YCKve4xUlb6ytr3PyOR0RK_50/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 133,
                'id_pameran' => 1,
                'id_kategori' => 3,
                'judul' => 'ARCA MOTION',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1BXrjz0EPYXb5SSczjmz2x-WBQWx5icJi/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 134,
                'id_pameran' => 1,
                'id_kategori' => 2,
                'judul' => 'PBL04GM12 Kelompok 3 Survei Batimetri dan Survei Kadastral Untuk Kadaster Kelautan (Marine Cadastre) di Tanjung Riau',
                'deskripsi' => '-',
                'tautan' => 'https://youtube.com/watch?v=q8F9zt9Zrmc&si=4JP_jkjYb6efdaRS',
                'gambar_poster' => 'https://drive.google.com/file/d/1_cKSuFHa3MabVbDTVXj1PnDe3Kegpbn_/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 135,
                'id_pameran' => 1,
                'id_kategori' => 8,
                'judul' => 'PBLEM25201 LED ARCADE GAME DIAMOND MODULE ASSEMBLY',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/18AaIwezp7B8O6xgBGnBf9PDvSbZQ55n5/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 136,
                'id_pameran' => 1,
                'id_kategori' => 8,
                'judul' => 'METALUMB',
                'deskripsi' => '-',
                'tautan' => 'https://youtube.com/watch?v=W8GAt2S9uLU&si=wN-fG4bZcvCP6nuJ',
                'gambar_poster' => 'https://drive.google.com/file/d/1jkjoRiUmvtvxYZfEjmjxC1LxHFIBbn87/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 137,
                'id_pameran' => 1,
                'id_kategori' => 8,
                'judul' => 'DIGITAL WALL CLOCK MODULE ASSEMBLY',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/Awowy24z7jM',
                'gambar_poster' => 'https://drive.google.com/file/d/1qOS92iRJbHglbPURDdyfBPMrsg_hQQC_/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 138,
                'id_pameran' => 1,
                'id_kategori' => 8,
                'judul' => 'MK2025A22P',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/18AaIwezp7B8O6xgBGnBf9PDvSbZQ55n5/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 139,
                'id_pameran' => 1,
                'id_kategori' => 8,
                'judul' => 'Barelang V-R2',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=9AKcTDI2bzE',
                'gambar_poster' => 'https://drive.google.com/file/d/1Fv1BXr7Wj0Y1qiEHi3whfyknavuryAIg/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 140,
                'id_pameran' => 1,
                'id_kategori' => 2,
                'judul' => 'GoSheep Team',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/tUXXa_WoUM8?si=NFt90ufNMqJcMjbJ',
                'gambar_poster' => 'https://drive.google.com/file/d/16EOYsZMPvFGUxR7vvjkliADRAxhNPNdG/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 141,
                'id_pameran' => 1,
                'id_kategori' => 2,
                'judul' => 'PBL RE 010 - Kontes Kapal Indonesia',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/7IuKOIUdmwA?si=-UMYLqdSKTsUctEw',
                'gambar_poster' => 'https://drive.google.com/file/d/1pgdTp5JhRlf4WNDzYG71xe0IlAw4hfO1/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 142,
                'id_pameran' => 1,
                'id_kategori' => 2,
                'judul' => 'DevFlow',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1v5SPvAvBoKjIDXNsI_vVlZ3V3K9-YUTG/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 143,
                'id_pameran' => 1,
                'id_kategori' => 2,
                'judul' => 'PBL04GM15',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/11RK8olgXJtvi3kYQdmMcaSb5LZim6TO-/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 144,
                'id_pameran' => 1,
                'id_kategori' => 2,
                'judul' => 'PBL04GM12 - Bathymetric Survey And Cadastral Survey For Marine Cadastre In Tanjung Riau',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1huUx5mZWX35O2O41WTYw6TGJBWi2qN_q/view',
                'gambar_poster' => 'https://drive.google.com/file/d/1zkMUIv6FvOJ8fZLMH49d3abpw1G75geU/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 145,
                'id_pameran' => 1,
                'id_kategori' => 2,
                'judul' => 'PBL04GM13 - Updating the Geoportal Database and the Internal Database in the Housing Sector',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=TNMuGHdHteI',
                'gambar_poster' => 'https://drive.google.com/file/d/1ao_yNQIKqNgNsn0QnVWBoF5jaMrE43Kn/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 146,
                'id_pameran' => 1,
                'id_kategori' => 2,
                'judul' => 'Farsight',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=lm5dglthkCk',
                'gambar_poster' => 'https://drive.google.com/file/d/1wHoQNiskBV5PX702D_cgDcAea91sVHjg/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 147,
                'id_pameran' => 1,
                'id_kategori' => 2,
                'judul' => 'IF-4PA-02',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/-kBuqZqk54o?si=YTf5wIg-atsddb-0',
                'gambar_poster' => 'https://drive.google.com/file/d/17jdvnDm2Pivt1Z2KyOVpYX2a5jbWxjb2/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 148,
                'id_pameran' => 1,
                'id_kategori' => 2,
                'judul' => 'Pocket Lite',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/ayf2ps4K-RI?si=tMKgGOFdnTGHPeu5',
                'gambar_poster' => 'https://drive.google.com/file/d/1W-iUqxHIv248ohX9A6DnILP69sdBxL87/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 149,
                'id_pameran' => 1,
                'id_kategori' => 2,
                'judul' => 'Meka22',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1rlrEsH-2zrwgJncZGMihiJIw9sSe0MTW/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 150,
                'id_pameran' => 1,
                'id_kategori' => 2,
                'judul' => 'PBL04GM12_Survei Batimetri dan Survei Kadastral Untuk Kadaster Kelautan (Marine Cadastre)_KELOMPOK2',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1ixv_RmSMqiGft1ipE0Ty_MMBr66QFd8o/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 151,
                'id_pameran' => 1,
                'id_kategori' => 8,
                'judul' => 'PBL ELECTROMETALLURGY',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1vQ9AyiNbfbnx6def1eSrEOVqQRtBcI2f/view?usp=sharing',
                'gambar_poster' => 'https://drive.google.com/file/d/1IxYKG19QNl7tO1PFfHXSDnDxDkuZ7jSa/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 152,
                'id_pameran' => 1,
                'id_kategori' => 1,
                'judul' => 'MYCONIK',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/KPZqXLawTyI?si=kQtvfi17jJuhsoFN',
                'gambar_poster' => 'https://drive.google.com/file/d/1zxn1DQFcTYi73abDhHQiH-Qg9Qs8bQ8z/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 153,
                'id_pameran' => 1,
                'id_kategori' => 1,
                'judul' => 'Ibu Doain Tim Kami Menang',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1Yq7Fu71CmI4Y0nciG9zPfxtBeZEtgOEr/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 154,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'kelompok pbl 17',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1gH485LhKMIYujtLMAnFcTZ-9dvkwAYnW/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 155,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'Barelang Marine Robotics Team - Autonomous Underwater Vehicle',
                'deskripsi' => '-',
                'tautan' => 'https://www.youtube.com/watch?v=dIKp2bO3Tq4&feature=youtu.be',
                'gambar_poster' => 'https://drive.google.com/file/d/1gH485LhKMIYujtLMAnFcTZ-9dvkwAYnW/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 156,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'PBL Group 19',
                'deskripsi' => '-',
                'tautan' => 'https://m.youtube.com/watch?v=ZwNos3rrc-Q&pp=iggCQAE%3D',
                'gambar_poster' => 'https://drive.google.com/file/d/1fP8mTmWH7Mg_285-o1dKc0BhhN-yDSAV/view?usp=drivesdk',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 157,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'Navtech Polibatam Team',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/XLvT_9Ca94Q?si=g7_spn27ZDfcNJ_6',
                'gambar_poster' => 'https://drive.google.com/file/d/1IfzJVjFiuRRoW-rRvKrdpifywjib63VP/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 158,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'BARELANG 63',
                'deskripsi' => '-',
                'tautan' => 'https://drive.google.com/file/d/1L14Hgero8u1N8eyHlUVXC2udfJ0e5oCn/view?usp=sharing',
                'gambar_poster' => 'https://drive.google.com/file/d/1x4U9b_DEGcNsqMTQfsD5ExmUDw6u7U6Q/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 159,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'IRONIC',
                'deskripsi' => '-',
                'tautan' => 'https://youtu.be/ym1dZiIj_uc?si=bCgv9Js56L3QJurB',
                'gambar_poster' => 'https://drive.google.com/file/d/1LpgN3wNvjHt3jxNCabNHNwzDIp2pi30y/view?usp=drive_link',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 160,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'PISN Kampung Seni Batam V2',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => 'https://drive.google.com/file/d/1jKf52CxgSb7GpB80nBhwHHD637R9yq-F/view?usp=sharing',
                'predikat' => null,
                'is_best' => null,
            ],
            [
                'id_admin' => 1,
                'id_stan' => 161,
                'id_pameran' => 1,
                'id_kategori' => 10,
                'judul' => 'PBL02GM10_Kelompok 3',
                'deskripsi' => '-',
                'tautan' => null,
                'gambar_poster' => null,
                'predikat' => null,
                'is_best' => null,
            ],
        ]);
    }
}